version: '3.8'

services:
  onlyfans-telegram-bot:
    build: .
    container_name: onlyfans-telegram-bot
    restart: unless-stopped
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./logs:/app/logs
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge 